name: facebook_desktop_webview_auth
description: This package enables Facebbok OAuth on desktop via webview
version: 0.0.2
homepage: https://github.com/invertase/flutter_desktop_webview_auth

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0'



dependencies:
  crypto: ^3.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: DesktopWebviewAuthPlugin

false_secrets:
  - /README.md
  - /example/lib/main.dart
  - /example/macos/Runner/GoogleService-Info.plist
